# Generated by Django 2.2.4 on 2021-03-05 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books_app', '0003_shelf_fixed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shelf',
            name='fixed',
            field=models.BooleanField(default=True),
        ),
    ]
