# Generated by Django 2.2.4 on 2021-03-05 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books_app', '0004_auto_20210305_0402'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shelf',
            name='fixed',
            field=models.BooleanField(default=False),
        ),
    ]
