# Generated by Django 2.2.4 on 2021-03-02 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='username',
            field=models.CharField(default='hello', max_length=255),
            preserve_default=False,
        ),
    ]
