# Generated by Django 2.2.4 on 2021-03-04 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_app', '0003_user_friends'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='added_friend',
            field=models.ManyToManyField(related_name='added_by', to='login_app.User'),
        ),
    ]
