# Generated by Django 2.2.4 on 2021-03-04 02:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login_app', '0004_user_added_friend'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='added_friend',
            new_name='added_friends',
        ),
    ]
